version: "3.8"

services:
    mongodb:
        container_name: mongodb
        image: mongo:5.0.2
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        ports:
            - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
        volumes:
            - db:/data/db
        networks:
            - backend

    user-api:
        container_name: user-api
        restart: unless-stopped
        build:
            context: ./backend/user-api
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - DB_HOST=mongodb
            - DB_USER=$MONGODB_USER
            - DB_PASSWORD=$MONGODB_PASSWORD
            - DB_NAME=$MONGODB_DATABASE
            - DB_PORT=$MONGODB_DOCKER_PORT
            - DEFAULT_USER=$NODE_DEFAULT_USER
        depends_on:
            - mongodb
        networks:
            - backend
            - frontend

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            args:
                - API_BASE_URL=$CLIENT_API_BASE_URL
        ports:
            - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
        depends_on:
            - user-api
        networks:
            - frontend

volumes:
    db:

networks:
    backend:
    frontend:
