version: "3.8"

services:
    mongodb:
        container_name: mongodb
        image: mongo:5.0.2
        restart: always
        env_file: ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        ports:
            - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
        volumes:
            - db:/data/db
        networks:
            - backend

    user-cache:
        container_name: user-cache
        image: redis:6.2-alpine
        restart: always
        env_file: ./.env
        ports:
            - $REDIS_PORT:$REDIS_PORT
        volumes:
            - cache:/data
        networks:
            - backend

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management-alpine
        restart: always
        env_file: ./.env
        ports:
            - $RABBIT_PORT:$RABBIT_PORT
            - $RABBIT_UI_PORT:$RABBIT_UI_PORT
        volumes:
            - './data/broker:/var/lib/rabbitmq/'
        networks:
            - backend

    user-queue:
        container_name: user-queue
        restart: on-failure
        build:
            context: ./backend/user-queue
        env_file: ./.env
        ports:
            - $USER_QUEUE_LOCAL_PORT:$USER_QUEUE_DOCKER_PORT
        environment:
            - DB_HOST=mongodb
            - DB_USER=$MONGODB_USER
            - DB_PASSWORD=$MONGODB_PASSWORD
            - DB_NAME=$MONGODB_DATABASE
            - DB_PORT=$MONGODB_DOCKER_PORT
            - DEFAULT_USER=$DEFAULT_USER
            - RABBIT_PORT:$RABBIT_PORT
            - RABBIT_HOST:$RABBIT_HOST
            - PORT:$USER_QUEUE_DOCKER_PORT
        networks:
            - backend

    user-api:
        container_name: user-api
        build:
            context: ./backend/user-api
        env_file: ./.env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - DB_HOST=mongodb
            - DB_USER=$MONGODB_USER
            - DB_PASSWORD=$MONGODB_PASSWORD
            - DB_NAME=$MONGODB_DATABASE
            - DB_PORT=$MONGODB_DOCKER_PORT
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
        networks:
            - backend
            - frontend

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            args:
                - API_BASE_URL=$CLIENT_API_BASE_URL
        ports:
            - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
        networks:
            - frontend

volumes:
    db:
    cache:

networks:
    backend:
    frontend:
